title: "Águia Pescadora por Etica.AI"
description: '“Águia Pescadora” é codinome atual usado pela Etica.AI tanto da implementação da núvem pública desta como da própria documentação de como pode ser recriada por terceiros.'
image:
  path: '/img/aguia-pescadora-banner.jpg'
  height: 640
  width: 1280

defaults:
  - scope:
      path: ""
    values:
      image: 
        path: '/img/aguia-pescadora-banner.jpg'
        height: 640
        width: 1280

# see https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
lang: 'pt'

twitter:
  username: EticaAI
  card: summary

plugins:
  - jekyll-seo-tag